%%begin highlights%%
try-catch

在solidity中，try-catch只能被用于external函数或创建合约时constructor（被视为external函数）的调用。基本语法如下：

try externalContract.f() {
// call成功的情况下 运行一些代码
} catch {
// call失败的情况下 运行一些代码
}

同样可以使用this.f()来替代externalContract.f()，this.f()也被视作为外部调用，但不可在构造函数中使用，因为此时合约还未创建。

如果调用的函数有返回值，那么必须在try之后声明returns(returnType val)，并且在try模块中可以使用返回的变量；如果是创建合约，那么返回值是新创建的合约变量。

try externalContract.f() returns(returnType val)

catch模块支持捕获特殊的异常原因：

catch Error(string memory reason) {
// 捕获失败的 revert() 和 require()
} catch (bytes memory reason) {
// 捕获失败的 assert()
}

用try-catch来处理合约创建时的异常。只需要把try模块改写为OnlyEven合约的创建就行：

try new OnlyEven(a) returns(OnlyEven _even){

try-catch来处理智能合约运行中的异常：
只能用于外部合约调用和合约创建。
如果try执行成功，返回变量必须声明，并且与返回的变量类型相同。
%%end highlights%%

!!!PAGE NOTE!!!
%%begin pagenote%%

%%end pagenote%%

[[星标]] #五彩插件 [原文](https://www.wtf.academy/solidity-advanced/TryCatch/)
更新时间: 2023-07-24 16:42